version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
      - /app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true

  server:
    image: theta/server
    build: ./server
    ports:
      - "4000:4000"
    volumes:
      - ./server:/usr/src/server
      - /usr/src/server/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:
